'use strict';
/**
 * workers/marketIntel.js — Daily market intelligence signal engine
 *
 * Runs automatically every 24 hours (or on-demand via /api/profile/signals/refresh).
 * Uses the user's SearchProfile (generated by profileSynthesizer) to:
 *
 *   1. Load regulatory deadlines from the Notion "Regulatory Deadlines" database
 *      (DB_REGULATORY env var). Zero hardcoded deadlines — all managed in Notion.
 *
 *   2. Search Google News RSS for 4 leading indicator types:
 *      - Leadership changes (new CTO/CIO at target companies)
 *      - Funding rounds (companies raising = hiring budget)
 *      - Tech/vendor purchases (platform adoption = impl. work)
 *      - Regulatory deadlines (compliance urgency)
 *
 *   3. Score each result against the user's profile (0-100)
 *      via profileSynthesizer.scoreSignal()
 *
 *   4. Cache results in-memory; Notion Signals DB persistence if configured
 *
 * ── Regulatory deadline source ────────────────────────────────────────────────
 * All deadlines live in a Notion database (DB_REGULATORY env var).
 * Add, edit, or deactivate entries directly in Notion — the app picks up
 * changes on the next refresh cycle (daily, or manual trigger).
 *
 * ── Why Google News RSS? ──────────────────────────────────────────────────────
 * Google News RSS (news.google.com/rss/search?q=...) is:
 *  - Completely free, no API key required
 *  - Updated in near real-time
 *  - Aggregates thousands of news sources globally
 *
 * ── Signal tiers ──────────────────────────────────────────────────────────────
 *  HOT     (75+): Strong match — act this week
 *  WARM    (50+): Good lead   — track and time your outreach
 *  MONITOR (25+): Weak match  — watch for development
 *  COLD    (<25): Irrelevant  — filtered out by default
 */

let RssParser;
try {
  RssParser = require('rss-parser');
} catch {
  RssParser = null;
}

let NotionClient;
try {
  NotionClient = require('@notionhq/client').Client;
} catch {
  NotionClient = null;
}

const { scoreSignal, scoreTier, generateSearchFilters, SIGNAL_TYPES } = require('../lib/profileSynthesizer');

// ── In-memory store ───────────────────────────────────────────────────────────

let _signals   = [];     // Latest scored signals
let _lastRun   = null;   // ISO timestamp of last successful run
let _running   = false;  // Prevent concurrent runs
let _profile   = null;   // Current user profile (set via setProfile)
let _filters   = null;   // Current search filters

// ── Notion client factory ─────────────────────────────────────────────────────

function notionClient() {
  const token = process.env.NOTION_TOKEN;
  if (!token || !NotionClient) return null;
  return new NotionClient({ auth: token });
}

// ── Regulatory deadlines — loaded from Notion ─────────────────────────────────
/**
 * Fetch all active regulatory deadlines from the Notion DB_REGULATORY database.
 * Returns an array of deadline objects shaped like:
 *   { name, deadline, description, keywords[], verticals[], link }
 *
 * Falls back to [] if Notion is unreachable or unconfigured.
 * Add/edit/deactivate entries directly in Notion — no code changes needed.
 */
async function loadRegulatoryDeadlines() {
  const dbId  = process.env.DB_REGULATORY;
  const nc    = notionClient();

  if (!dbId || !nc) {
    if (!dbId) console.warn('[marketIntel] DB_REGULATORY not set — no regulatory signals');
    return [];
  }

  try {
    const rows = [];
    let cursor;

    // Paginate through all active entries
    do {
      const resp = await nc.databases.query({
        database_id:  dbId,
        filter:       { property: 'Active', checkbox: { equals: true } },
        page_size:    100,
        start_cursor: cursor,
      });
      rows.push(...resp.results);
      cursor = resp.has_more ? resp.next_cursor : undefined;
    } while (cursor);

    return rows.map(page => {
      const p = page.properties;

      // Extract title
      const name = p.Name?.title?.map(t => t.plain_text).join('') || '';

      // Extract deadline date
      const deadline = p.Deadline?.date?.start || null;

      // Extract rich text fields
      const description = p.Description?.rich_text?.map(t => t.plain_text).join('') || '';
      const keywordsRaw = p.Keywords?.rich_text?.map(t => t.plain_text).join('') || '';
      const keywords    = keywordsRaw.split(',').map(k => k.trim()).filter(Boolean);

      // Extract multi-select verticals
      const verticals = (p.Verticals?.multi_select || []).map(opt => opt.name);

      // Optional official link
      const link = p['Official Link']?.url || null;

      return { name, deadline, description, keywords, verticals, link };
    }).filter(d => d.name && d.deadline); // drop incomplete rows

  } catch (e) {
    console.warn(`[marketIntel] failed to load regulatory deadlines from Notion: ${e.message}`);
    return [];
  }
}

// ── Google News RSS builder ───────────────────────────────────────────────────

const GN_BASE = 'https://news.google.com/rss/search';

function buildGoogleNewsUrl(query, lang = 'en', geo = 'NL') {
  const params = new URLSearchParams({
    q:    query,
    hl:   lang,
    gl:   geo,
    ceid: `${geo}:${lang}`,
  });
  return `${GN_BASE}?${params}`;
}

// ── Parse a single RSS item into a signal ─────────────────────────────────────

function parseRssItem(item, queryType, queryWeight) {
  const pubDate = item.pubDate || item.isoDate || null;
  return {
    id:          `${item.guid || item.link || Math.random().toString(36).slice(2)}`,
    title:       item.title  || item.contentSnippet || 'Untitled',
    description: item.contentSnippet || item.content || '',
    link:        item.link   || null,
    source:      item.creator || item['dc:creator'] || extractSource(item.link),
    publishedAt: pubDate ? new Date(pubDate).toISOString() : new Date().toISOString(),
    type:        queryType,
    weight:      queryWeight,
    score:       0,
    tier:        'COLD',
  };
}

function extractSource(url) {
  if (!url) return 'News';
  try { return new URL(url).hostname.replace('www.', ''); }
  catch { return 'News'; }
}

// ── Regulatory deadline → signal conversion ───────────────────────────────────
/**
 * Turn a raw deadline row (from Notion) into a scored signal if it falls
 * within the relevant window:
 *   - Upcoming  (≤365 days): golden planning window
 *   - Remediation (≤90 days past): clean-up work typically ongoing
 *
 * Base scores are derived from urgency/proximity — these signals are already
 * pre-filtered to profile-relevant verticals, so they bypass keyword matching.
 */
function deadlineToSignal(reg, profile) {
  const profileInds = (profile?.industries || []).map(i => i.toLowerCase());

  // Only include if profile verticals overlap with this regulation
  if (reg.verticals.length > 0) {
    const relevant = reg.verticals.some(v =>
      profileInds.some(pi =>
        pi.includes(v.toLowerCase()) || v.toLowerCase().includes(pi)
      )
    );
    if (!relevant) return null;
  }

  const now        = Date.now();
  const deadlineMs = new Date(reg.deadline).getTime();
  const daysUntil  = (deadlineMs - now) / (1000 * 60 * 60 * 24);
  const daysSince  = (now - deadlineMs) / (1000 * 60 * 60 * 24);

  // Determine urgency window
  let urgency = null;
  if      (daysUntil > 0 && daysUntil <= 180)  urgency = 'upcoming';
  else if (daysUntil > 0 && daysUntil <= 365)   urgency = 'planning_horizon';
  else if (daysSince >= 0 && daysSince <= 90)    urgency = 'remediation';

  if (!urgency) return null; // too far out or too old

  // Base relevance score (pre-verified for profile fit)
  const baseScore = urgency === 'upcoming'
    ? (daysUntil < 60 ? 72 : daysUntil < 120 ? 65 : 55)
    : urgency === 'remediation'
    ? (daysSince < 30 ? 68 : 55)
    : 48; // planning_horizon

  const icon = urgency === 'upcoming' ? '⏰' : urgency === 'remediation' ? '🔧' : '📅';
  const timeLabel = daysUntil > 0
    ? ` Deadline: ${Math.round(daysUntil)} days away.`
    : ` ${Math.round(daysSince)} days since deadline — remediation work typically ongoing for 90 days.`;

  return {
    id:          `reg-${reg.name.replace(/\s+/g, '-').toLowerCase().slice(0, 60)}`,
    title:       `${icon} ${reg.name}`,
    description: reg.description + timeLabel,
    link:        reg.link || null,
    source:      'Regulatory Calendar',
    publishedAt: new Date().toISOString(),
    type:        SIGNAL_TYPES.REGULATORY,
    weight:      urgency === 'upcoming' ? 35 : urgency === 'remediation' ? 25 : 15,
    urgency,
    keywords:    reg.keywords,
    _preScore:   baseScore,
  };
}

// ── Main refresh function ─────────────────────────────────────────────────────

/**
 * Fetch fresh signals using current search filters.
 * Called by the scheduler (daily) or manually via API.
 *
 * @returns {Promise<Signal[]>} Scored and sorted signals
 */
async function refresh() {
  if (_running) {
    console.log('[marketIntel] refresh already in progress, skipping');
    return _signals;
  }
  if (!_profile) {
    console.log('[marketIntel] no profile set — run /api/profile/confirm first');
    return _signals;
  }

  _running = true;
  console.log('[marketIntel] starting signal refresh…');
  const started = Date.now();

  const raw = [];

  // 1. Regulatory signals — loaded from Notion (zero hardcoded)
  const deadlines   = await loadRegulatoryDeadlines();
  const regSignals  = deadlines
    .map(d => deadlineToSignal(d, _profile))
    .filter(Boolean);
  raw.push(...regSignals);
  console.log(`[marketIntel] loaded ${deadlines.length} deadlines from Notion → ${regSignals.length} relevant signals`);

  // 2. Live news via Google News RSS (if rss-parser is available)
  if (RssParser && _filters?.newsQueries?.length) {
    const parser = new RssParser({ timeout: 8000, headers: { 'User-Agent': 'Nexus-Intel/1.0' } });

    for (const nq of _filters.newsQueries) {
      const geo = _filters.geographies?.includes('Netherlands') ? 'NL' : 'GB';
      const url = buildGoogleNewsUrl(nq.query, 'en', geo);

      try {
        const feed  = await parser.parseURL(url);
        const items = (feed.items || []).slice(0, 8).map(item =>
          parseRssItem(item, nq.type, nq.weight)
        );
        raw.push(...items);
      } catch (e) {
        // RSS fetch fails silently — don't block on individual sources
        console.warn(`[marketIntel] RSS fetch failed for "${nq.type}": ${e.message}`);
      }

      await new Promise(r => setTimeout(r, 300)); // brief pause to avoid rate limiting
    }
  }

  // 3. Score all signals against profile
  const scored = raw.map(signal => {
    const score = signal._preScore != null
      ? Math.min(100, signal._preScore)  // use pre-computed relevance score
      : scoreSignal(signal, _profile);   // compute from keywords/industries
    const { _preScore: _, ...rest } = signal;
    return { ...rest, score, tier: scoreTier(score) };
  });

  // 4. Deduplicate by title similarity
  const deduped = deduplicateSignals(scored);

  // 5. Sort: HOT first, then WARM, then by score desc; filter COLD noise
  _signals = deduped
    .filter(s => s.tier !== 'COLD')
    .sort((a, b) => b.score - a.score);

  _lastRun = new Date().toISOString();
  _running = false;

  console.log(`[marketIntel] refresh complete: ${_signals.length} signals (${Date.now() - started}ms)`);
  return _signals;
}

// ── Deduplication ─────────────────────────────────────────────────────────────

function normalizeTitle(t) {
  return t.toLowerCase().replace(/[^a-z0-9\s]/g, '').trim();
}

function similarity(a, b) {
  const wordsA = new Set(normalizeTitle(a).split(/\s+/).filter(w => w.length > 3));
  const wordsB = new Set(normalizeTitle(b).split(/\s+/).filter(w => w.length > 3));
  const intersection = [...wordsA].filter(w => wordsB.has(w)).length;
  const union = new Set([...wordsA, ...wordsB]).size;
  return union === 0 ? 0 : intersection / union;
}

function deduplicateSignals(signals) {
  const kept = [];
  for (const sig of signals) {
    const isDup = kept.some(k => similarity(k.title, sig.title) > 0.6);
    if (!isDup) kept.push(sig);
  }
  return kept;
}

// ── Profile + filter management ───────────────────────────────────────────────

function setProfile(profile) {
  _profile = profile;
  _filters = generateSearchFilters(profile);
  console.log('[marketIntel] profile set —', _filters.keywords.slice(0, 5).join(', '), '…');
}

function getProfile()  { return _profile; }
function getFilters()  { return _filters; }
function getSignals()  { return _signals; }
function getLastRun()  { return _lastRun; }
function getMeta()     {
  return {
    signalCount:       _signals.length,
    hot:               _signals.filter(s => s.tier === 'HOT').length,
    warm:              _signals.filter(s => s.tier === 'WARM').length,
    monitor:           _signals.filter(s => s.tier === 'MONITOR').length,
    lastRun:           _lastRun,
    hasProfile:        !!_profile,
    profileConfidence: _profile?.confidence ?? 0,
  };
}

// ── Scheduler ─────────────────────────────────────────────────────────────────

let _refreshInterval = null;

function startScheduler(intervalMs = 24 * 60 * 60 * 1000) {
  if (_refreshInterval) return;
  _refreshInterval = setInterval(async () => {
    if (!_profile) return;
    try { await refresh(); }
    catch (e) { console.error('[marketIntel] scheduled refresh failed:', e.message); }
  }, intervalMs);
  console.log(`[marketIntel] scheduler started (interval: ${intervalMs / 3600000}h)`);
}

function stopScheduler() {
  if (_refreshInterval) {
    clearInterval(_refreshInterval);
    _refreshInterval = null;
  }
}

module.exports = {
  refresh,
  setProfile,
  getProfile,
  getFilters,
  getSignals,
  getLastRun,
  getMeta,
  startScheduler,
  stopScheduler,
};
