'use strict';
/**
 * workers/marketIntel.js — Daily market intelligence signal engine
 *
 * Runs automatically every 24 hours (or on-demand via /api/profile/signals/refresh).
 * Uses the user's SearchProfile (generated by profileSynthesizer) to:
 *
 *   1. Search Google News RSS for 4 leading indicator types:
 *      - Leadership changes (new CTO/CIO at target companies)
 *      - Funding rounds (companies raising = hiring budget)
 *      - Tech/vendor purchases (platform adoption = impl. work)
 *      - Regulatory deadlines (compliance urgency)
 *
 *   2. Optionally scan job boards (extending jobFeed.js with profile keywords)
 *
 *   3. Score each result against the user's profile (0-100)
 *      via profileSynthesizer.scoreSignal()
 *
 *   4. Cache results in-memory, persist to Notion Signals DB if configured
 *
 * The worker is stateless: it reads the current SearchFilters, runs queries,
 * scores results, and updates the in-memory store. The frontend polls
 * GET /api/profile/signals for the latest scored results.
 *
 * ── Why Google News RSS? ──────────────────────────────────────────────────────
 * Google News RSS (news.google.com/rss/search?q=...) is:
 *  - Completely free, no API key required
 *  - Updated in near real-time
 *  - Aggregates thousands of news sources globally
 *  - Filterable by query string, language, and region
 *
 * ── Signal types produced ─────────────────────────────────────────────────────
 *  HOT   (75+): Strong match — act this week
 *  WARM  (50+): Good lead   — track and time your outreach
 *  MONITOR (25+): Weak match — watch for development
 *  COLD   (<25): Irrelevant — filtered out by default
 */

let RssParser;
try {
  RssParser = require('rss-parser');
} catch {
  RssParser = null;
}

const { scoreSignal, scoreTier, generateSearchFilters, SIGNAL_TYPES } = require('../lib/profileSynthesizer');

// ── In-memory store ───────────────────────────────────────────────────────────

let _signals   = [];          // Latest scored signals
let _lastRun   = null;        // ISO timestamp of last successful run
let _running   = false;       // Prevent concurrent runs
let _profile   = null;        // Current user profile (set via setProfile)
let _filters   = null;        // Current search filters

// ── Google News RSS builder ───────────────────────────────────────────────────

const GN_BASE = 'https://news.google.com/rss/search';

function buildGoogleNewsUrl(query, lang = 'en', geo = 'NL') {
  const params = new URLSearchParams({
    q:    query,
    hl:   lang,
    gl:   geo,
    ceid: `${geo}:${lang}`,
  });
  return `${GN_BASE}?${params}`;
}

// ── Known regulatory deadlines (static knowledge base) ────────────────────────
// These become signals when they're within the "golden window" before the deadline.

const REGULATORY_DEADLINES = [
  {
    name:        'DORA — Digital Operational Resilience Act',
    deadline:    '2025-01-17',
    description: 'EU financial sector must comply with DORA ICT risk management and incident reporting requirements.',
    keywords:    ['DORA', 'digital resilience', 'ICT risk', 'financial sector'],
    verticals:   ['Asset Management', 'Banking', 'Insurance'],
    type:        SIGNAL_TYPES.REGULATORY,
  },
  {
    name:        'NIS2 Directive implementation',
    deadline:    '2024-10-17',
    description: 'EU member states must implement NIS2 cybersecurity directive for critical infrastructure.',
    keywords:    ['NIS2', 'cybersecurity', 'critical infrastructure', 'incident reporting'],
    verticals:   ['Banking', 'Healthcare', 'Energy & Sustainability', 'Cloud / Infrastructure'],
    type:        SIGNAL_TYPES.REGULATORY,
  },
  {
    name:        'SFDR Level 2 — Sustainable Finance Disclosure',
    deadline:    '2023-01-01',
    description: 'Asset managers must report ESG metrics, portfolio sustainability indicators under SFDR L2.',
    keywords:    ['SFDR', 'ESG', 'sustainability reporting', 'Article 8', 'Article 9'],
    verticals:   ['Asset Management', 'Private Equity / VC', 'Pension Funds'],
    type:        SIGNAL_TYPES.REGULATORY,
  },
  {
    name:        'EMIR Refit — Reporting overhaul deadline',
    deadline:    '2024-04-29',
    description: 'Derivatives reporting overhaul requiring firms to submit new EMIR data fields.',
    keywords:    ['EMIR', 'derivatives reporting', 'trade repository', 'UTI'],
    verticals:   ['Capital Markets', 'Asset Management', 'Banking'],
    type:        SIGNAL_TYPES.REGULATORY,
  },
  {
    name:        'AI Act — EU Artificial Intelligence Regulation',
    deadline:    '2026-08-02',
    description: 'High-risk AI systems must comply with EU AI Act requirements.',
    keywords:    ['EU AI Act', 'AI regulation', 'high-risk AI', 'AI compliance'],
    verticals:   ['AI / Machine Learning', 'Banking', 'Healthcare', 'Compliance & Regulatory'],
    type:        SIGNAL_TYPES.REGULATORY,
  },
  {
    name:        'Basel IV implementation',
    deadline:    '2025-01-01',
    description: 'Banks must implement Basel IV capital requirements framework.',
    keywords:    ['Basel IV', 'capital requirements', 'credit risk', 'operational risk'],
    verticals:   ['Banking', 'Capital Markets'],
    type:        SIGNAL_TYPES.REGULATORY,
  },
  // ── Upcoming 2026–2027 deadlines ─────────────────────────────────────────────
  {
    name:        'CSRD — Corporate Sustainability Reporting Directive',
    deadline:    '2026-01-01',
    description: 'Large EU non-listed companies and SMEs must publish ESG sustainability reports under CSRD (EU taxonomy, double materiality).',
    keywords:    ['CSRD', 'sustainability reporting', 'double materiality', 'EU taxonomy', 'ESG reporting'],
    verticals:   ['Asset Management', 'Private Equity / VC', 'Pension Funds', 'Banking'],
    type:        SIGNAL_TYPES.REGULATORY,
  },
  {
    name:        'T+1 Settlement — EU & UK equity markets',
    deadline:    '2027-10-11',
    description: 'EU and UK equity markets move to T+1 settlement cycle, requiring significant back-office and custody system upgrades.',
    keywords:    ['T+1', 'settlement', 'custody', 'CSDR', 'back office', 'clearing'],
    verticals:   ['Capital Markets', 'Asset Management', 'Banking'],
    type:        SIGNAL_TYPES.REGULATORY,
  },
  {
    name:        'MiCA — Markets in Crypto-Assets Regulation',
    deadline:    '2026-12-30',
    description: 'Full MiCA implementation: crypto-asset service providers need authorisation, stablecoin issuers face reserve requirements.',
    keywords:    ['MiCA', 'crypto-assets', 'stablecoin', 'CASP', 'crypto regulation', 'digital assets'],
    verticals:   ['Capital Markets', 'Banking', 'Asset Management'],
    type:        SIGNAL_TYPES.REGULATORY,
  },
  {
    name:        'DORA — ICT Third-Party Risk (first supervisory cycle)',
    deadline:    '2026-04-30',
    description: 'Financial entities must complete first DORA ICT third-party risk register and TLPT (threat-led penetration testing) cycles.',
    keywords:    ['DORA', 'ICT third-party', 'TLPT', 'penetration testing', 'digital operational resilience'],
    verticals:   ['Asset Management', 'Banking', 'Insurance'],
    type:        SIGNAL_TYPES.REGULATORY,
  },
  {
    name:        'AIFMD II — Alternative Investment Fund Managers Directive',
    deadline:    '2026-04-16',
    description: 'EU member states must transpose AIFMD II: new delegation rules, liquidity management tools, and loan-originating fund requirements.',
    keywords:    ['AIFMD II', 'alternative investment', 'delegation', 'loan originating', 'liquidity management'],
    verticals:   ['Asset Management', 'Private Equity / VC'],
    type:        SIGNAL_TYPES.REGULATORY,
  },
  {
    name:        'PRIIPS KID Review — Retail Investment Strategy',
    deadline:    '2026-12-31',
    description: 'Revised PRIIPS Key Information Document rules under the EU Retail Investment Strategy; asset managers must update fund KIDs.',
    keywords:    ['PRIIPS', 'KID', 'retail investment', 'key information document', 'fund documentation'],
    verticals:   ['Asset Management', 'Pension Funds'],
    type:        SIGNAL_TYPES.REGULATORY,
  },
];

// ── Parse a single RSS item into a signal ─────────────────────────────────────

function parseRssItem(item, queryType, queryWeight) {
  const pubDate = item.pubDate || item.isoDate || null;
  return {
    id:          `${item.guid || item.link || Math.random().toString(36).slice(2)}`,
    title:       item.title  || item.contentSnippet || 'Untitled',
    description: item.contentSnippet || item.content || '',
    link:        item.link   || null,
    source:      item.creator || item['dc:creator'] || extractSource(item.link),
    publishedAt: pubDate ? new Date(pubDate).toISOString() : new Date().toISOString(),
    type:        queryType,
    weight:      queryWeight,
    score:       0,
    tier:        'COLD',
  };
}

function extractSource(url) {
  if (!url) return 'News';
  try {
    return new URL(url).hostname.replace('www.', '');
  } catch {
    return 'News';
  }
}

// ── Regulatory deadline signals ───────────────────────────────────────────────
// Generate synthetic signals from known regulatory deadlines that are either:
//   - Upcoming in the next 180 days (golden window = companies scrambling)
//   - Passed within the last 30 days (immediate remediation work)

function generateRegulatorySignals(profile) {
  const profileInds = (profile?.industries || []).map(i => i.toLowerCase());
  const now         = Date.now();
  const signals     = [];

  for (const reg of REGULATORY_DEADLINES) {
    // Only include if profile verticals overlap
    const relevantToProfile = reg.verticals.some(v =>
      profileInds.some(pi => pi.includes(v.toLowerCase()) || v.toLowerCase().includes(pi))
    );
    if (!relevantToProfile) continue;

    const deadlineMs = new Date(reg.deadline).getTime();
    const daysUntil  = (deadlineMs - now) / (1000 * 60 * 60 * 24);
    const daysSince  = (now - deadlineMs) / (1000 * 60 * 60 * 24);

    let urgency = null;
    if (daysUntil > 0 && daysUntil <= 180)      urgency = 'upcoming';
    else if (daysUntil > 0 && daysUntil <= 365)  urgency = 'planning_horizon';
    else if (daysSince >= 0 && daysSince <= 90)   urgency = 'remediation';

    if (!urgency) continue;

    // Base score for regulatory signals (already pre-filtered for profile relevance)
    const baseScore = urgency === 'upcoming'
      ? (daysUntil < 60 ? 72 : daysUntil < 120 ? 65 : 55)
      : urgency === 'remediation'
      ? (daysSince < 30 ? 68 : 55)
      : 48;

    const signal = {
      id:          `reg-${reg.name.replace(/\s+/g, '-').toLowerCase()}`,
      title:       `${urgency === 'upcoming' ? '⏰ ' : urgency === 'remediation' ? '🔧 ' : '📅 '}${reg.name}`,
      description: reg.description + (daysUntil > 0
        ? ` Deadline: ${Math.round(daysUntil)} days away.`
        : ` ${Math.round(daysSince)} days since deadline — remediation work typically ongoing for 90 days.`),
      link:        null,
      source:      'Regulatory Calendar',
      publishedAt: new Date().toISOString(), // treat as today for recency
      type:        SIGNAL_TYPES.REGULATORY,
      weight:      urgency === 'upcoming' ? 35 : urgency === 'remediation' ? 25 : 15,
      urgency,
      keywords:    reg.keywords,
      // Pre-score: already verified relevant to profile verticals
      _preScore:   baseScore,
    };

    signals.push(signal);
  }

  return signals;
}

// ── Main refresh function ─────────────────────────────────────────────────────

/**
 * Fetch fresh signals using current search filters.
 * Called by the scheduler (daily) or manually via API.
 *
 * @returns {Promise<Signal[]>} Scored and sorted signals
 */
async function refresh() {
  if (_running) {
    console.log('[marketIntel] refresh already in progress, skipping');
    return _signals;
  }
  if (!_profile) {
    console.log('[marketIntel] no profile set — run /api/profile/confirm first');
    return _signals;
  }

  _running = true;
  console.log('[marketIntel] starting signal refresh…');
  const started = Date.now();

  const raw = [];

  // 1. Regulatory signals (always included — derived from static knowledge)
  const regSignals = generateRegulatorySignals(_profile);
  raw.push(...regSignals);

  // 2. Live news via Google News RSS (if rss-parser is available)
  if (RssParser && _filters?.newsQueries?.length) {
    const parser = new RssParser({ timeout: 8000, headers: { 'User-Agent': 'Nexus-Intel/1.0' } });

    for (const nq of _filters.newsQueries) {
      const geo = _filters.geographies?.includes('Netherlands') ? 'NL' : 'GB';
      const url = buildGoogleNewsUrl(nq.query, 'en', geo);

      try {
        const feed = await parser.parseURL(url);
        const items = (feed.items || []).slice(0, 8).map(item =>
          parseRssItem(item, nq.type, nq.weight)
        );
        raw.push(...items);
      } catch (e) {
        // RSS fetch can fail silently — we don't block on individual sources
        console.warn(`[marketIntel] RSS fetch failed for "${nq.type}": ${e.message}`);
      }

      // Brief pause to avoid rate limiting
      await new Promise(r => setTimeout(r, 300));
    }
  }

  // 3. Score all signals against profile
  // Pre-scored signals (regulatory, already filtered for profile relevance) use their _preScore
  const scored = raw.map(signal => {
    const score = signal._preScore != null
      ? Math.min(100, signal._preScore)   // use pre-computed relevance score
      : scoreSignal(signal, _profile);    // compute from keywords/industries
    const { _preScore: _, ...rest } = signal;
    return { ...rest, score, tier: scoreTier(score) };
  });

  // 4. Deduplicate by title similarity (remove near-duplicates from multiple RSS sources)
  const deduped = deduplicateSignals(scored);

  // 5. Sort: HOT first, then WARM, then by score
  const sorted = deduped
    .filter(s => s.tier !== 'COLD')  // filter noise by default
    .sort((a, b) => b.score - a.score);

  _signals = sorted;
  _lastRun = new Date().toISOString();
  _running = false;

  console.log(`[marketIntel] refresh complete: ${sorted.length} signals (${Date.now() - started}ms)`);
  return _signals;
}

// ── Deduplication ─────────────────────────────────────────────────────────────

function normalizeTitle(t) {
  return t.toLowerCase().replace(/[^a-z0-9\s]/g, '').trim();
}

function similarity(a, b) {
  const wordsA = new Set(normalizeTitle(a).split(/\s+/).filter(w => w.length > 3));
  const wordsB = new Set(normalizeTitle(b).split(/\s+/).filter(w => w.length > 3));
  const intersection = [...wordsA].filter(w => wordsB.has(w)).length;
  const union = new Set([...wordsA, ...wordsB]).size;
  return union === 0 ? 0 : intersection / union;
}

function deduplicateSignals(signals) {
  const kept = [];
  for (const sig of signals) {
    const isDup = kept.some(k => similarity(k.title, sig.title) > 0.6);
    if (!isDup) kept.push(sig);
  }
  return kept;
}

// ── Profile + filter management ───────────────────────────────────────────────

function setProfile(profile) {
  _profile = profile;
  _filters = generateSearchFilters(profile);
  console.log('[marketIntel] profile set —', _filters.keywords.slice(0, 5).join(', '), '…');
}

function getProfile()  { return _profile; }
function getFilters()  { return _filters; }
function getSignals()  { return _signals; }
function getLastRun()  { return _lastRun; }
function getMeta()     {
  return {
    signalCount:  _signals.length,
    hot:          _signals.filter(s => s.tier === 'HOT').length,
    warm:         _signals.filter(s => s.tier === 'WARM').length,
    monitor:      _signals.filter(s => s.tier === 'MONITOR').length,
    lastRun:      _lastRun,
    hasProfile:   !!_profile,
    profileConfidence: _profile?.confidence ?? 0,
  };
}

// ── Scheduler integration ─────────────────────────────────────────────────────
// Called by lib/scheduler.js — runs once per day after midnight.

let _refreshInterval = null;

function startScheduler(intervalMs = 24 * 60 * 60 * 1000) {
  if (_refreshInterval) return; // already running
  _refreshInterval = setInterval(async () => {
    if (!_profile) return;
    try { await refresh(); }
    catch (e) { console.error('[marketIntel] scheduled refresh failed:', e.message); }
  }, intervalMs);
  console.log(`[marketIntel] scheduler started (interval: ${intervalMs / 3600000}h)`);
}

function stopScheduler() {
  if (_refreshInterval) {
    clearInterval(_refreshInterval);
    _refreshInterval = null;
  }
}

module.exports = {
  refresh,
  setProfile,
  getProfile,
  getFilters,
  getSignals,
  getLastRun,
  getMeta,
  startScheduler,
  stopScheduler,
};
